---
- name: Grafana, Prometheus and Apache node exporter configuration
  hosts: all
  become: true
  vars_files: vars.yml
  tasks:
    - name: Copy prometheus.yml (Config file)to server
      ansible.builtin.copy:
        src: ../monitoring_conf/prometheus_conf/prometheus.yml
        dest: "{{ prometheus_conf }}/prometheus.yml"
        mode: '0644'
      notify: Restart prometheus

    - name: tls_config_exporter.yml (Config file)to server
      ansible.builtin.copy:
        src: ../monitoring_conf/prometheus_conf/tls_config_exporter.yml
        dest: "{{ prometheus_conf }}/tls_config_exporter.yml"
        mode: '0644'
      notify: Restart prometheus-apache-exporter

    - name: Copy grafana datasources to server
      ansible.builtin.copy:
        src: ../monitoring_conf/grafana_conf/datasources/
        dest: "{{ grafana_datasources }}"
        mode: '0644'
      notify: Restart grafana-server

    - name: Create the destination folder
      ansible.builtin.file:
        path: /var/lib/grafana/dashboards
        state: directory
        mode: '0755'

    - name: Copy grafana dashboard json files to server
      ansible.builtin.copy:
        src: ../monitoring_conf/grafana_conf/dashboards_conf/dashboards/
        dest: "{{ grafana_dashboards_json }}"
        mode: '0644'
      notify: Restart grafana-server

    - name: Copy grafana dashboards config file to server
      ansible.builtin.copy:
        src: ../monitoring_conf/grafana_conf/dashboards_conf/config/
        dest: "{{ grafana_dashboards_config }}"
        mode: '0644'
      notify: Restart grafana-server

    - name: Copy grafana.ini
      ansible.builtin.copy:
        src: ../monitoring_conf/grafana_conf/grafana.ini
        dest: "/etc/grafana/"
        mode: '0644'
      notify: Restart grafana-server

    - name: Copy all systemd arguments for prometheus & its services(for listening locally)
      ansible.builtin.copy:
        src: ../monitoring_conf/prometheus_conf/systemd_args/
        dest: /etc/default
        mode: '0644'
      notify:
        - Restart prometheus
        - Restart prometheus-node-exporter
        - Restart prometheus-apache-exporter


    - name: Reload systemd to apply new configurations
      ansible.builtin.systemd:
        daemon_reload: yes
      notify:
        - Restart prometheus
        - Restart prometheus-node-exporter
        - Restart prometheus-apache-exporter

  handlers:
    - name: Restart prometheus
      ansible.builtin.service:
        name: prometheus
        state: restarted

    - name: Restart prometheus-node-exporter
      ansible.builtin.service:
        name: prometheus-node-exporter
        state: restarted

    - name: Restart prometheus-apache-exporter
      ansible.builtin.service:
        name: prometheus-apache-exporter
        state: restarted

    - name: Restart grafana-server
      ansible.builtin.service:
        name: grafana-server
        state: restarted
        enabled: yes
